# Settings for Daedalus TCU

[tcu]
address = "tcp://localhost"
port = 5556

[lakeshore]
sensor1 = "KRDG?A"
sensor2 = "KRDG?B"
address = "192.168.207.120"
port = 7777

[maxigauge]
address = "192.168.207.167"
port = 8000
