# Settings for Daedalus MCU

[mcu]
address = "tcp://*"
port = 5556
update_rate = 1 # in seconds
num_average = 4

# Pressure sensor for nozzle
[nozpressure]
cal_points = [[82, 1097], [40, 2249]]

# Configuration for MCP23S08

[mcp23s08_0]
spi_bus = 0
spi_cs = 0
spi_max_speed_hz = 5000
cs_pin = 24

[mcp23s08_1]
spi_bus = 1
spi_cs = 0
spi_max_speed_hz = 5000
cs_pin = 26

# Configuration for MCP3208

[mcp3208_0]
spi_bus = 0
spi_cs = 1
spi_max_speed_hz = 5000
cs_pin = 12

[mcp3208_1]
spi_bus = 1
spi_cs = 1
spi_max_speed_hz = 5000
cs_pin = 11
