# Settings for Daedalus MCU

[mcu]
address = "tcp://*"
port = 5556
update_rate = 0.5 # in seconds

# Pressure sensor for nozzle
[nozzle_sensor]
cal_points = [[0.64, 3.23], [0, 60]] # voltage [V] vs. pressure in [bar] (based on datasheet)

[pot_x]
cal_points = [[0.64, 3.23], [0, 60]] # voltage [V] vs. position [mm]

[pot_z]
cal_points = [[0.64, 3.23], [0, 60]] # voltage [V] vs. position [mm]

# Configuration for MCP3208

[mcp3208_0]
spi_bus = 0
spi_cs = 1
spi_max_speed_hz = 5000
num_average = 4
