# Settings for Daedalus TCU

[tcu]
address = "tcp://localhost"
port = port_number

[grafana]
address = "tcp://localhost"
port = port_number
org = "myorg"
bucket = "myexperiment"
token = "mytoken"

[lakeshore]
sensor1 = "sensor1_label"
sensor2 = "sensor2_label"
address = "tcp://localhost"
port = port_number

[multigauge]
address = "tcp://localhost"
port = port_number
