{
 "title": "Daedalus gas-jet",
 "description": "CRYRING Gasjet supervision through Daedalus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "Ring_gauge",
    "query": "YR09_Etarget, YR09_CARME, YR09VM1G, YR09VM2G"
   }
  ]
 },
 "panels": [
  {
   "title": "Nozzle Pressure (bar)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"experiment\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pressure\" and r[\"dev\"] == \"nozzle\")\r\n  |> last()\r\n  |> drop(columns: [\"raw\"])\r\n"
    }
   ]
  },
  {
   "title": "Target gas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"experiment\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"density\" and r[\"dev\"] == \"GJ\" and r._field == \"species\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 4, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"experiment\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\" and r[\"dev\"] =~ /GJ_Coldhead/)\n  |> aggregateWindow(every: v.windowPeriod, fn: last)"
    }
   ]
  },
  {
   "title": "Temp (K)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"experiment\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\" and r[\"dev\"] =~ /GJ_Coldhead/)\n  |> last()"
    }
   ]
  },
  {
   "title": "Nozzle position (mm)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"experiment\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"position\" and r[\"dev\"] == \"nozzle\")\r\n  |> last()\r\n  |> drop(columns: [\"raw\"])\r\n  \r\n"
    }
   ]
  },
  {
   "title": "Inlet pressures (mbar)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"experiment\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vacuum\" and r[\"dev\"] =~ /GJ_E/)\n  |> last()"
    }
   ]
  },
  {
   "title": "Density",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "query": "from(bucket: \"experiment\")\n|> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"density\" and r[\"dev\"] == \"GJ\")\n|> aggregateWindow(every: v.windowPeriod, fn: last)"
    }
   ]
  },
  {
   "title": "Density (1/cm^2)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"experiment\")\n|> range(start: -5m)\n|> filter(fn: (r) => r[\"_measurement\"] == \"density\" and r[\"dev\"] == \"GJ\")\n|> last()"
    }
   ]
  },
  {
   "type": "text",
   "description": "Gasjet control",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 13 },
   "options": {
    "content": "<h2>Daedalus</h2>\n<p>\n<img src=\"https://raw.githubusercontent.com/xaratustrah/daedalus/refs/heads/main/rsrc/daedalus.jpg\" />\n</p>\n<p>\nProject on <a href=\"https://github.com/xaratustrah/daedalus/\">GitHub</a>\n</p>"
   }
  },
  {
   "title": "Shutter",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"experiment\")\n|> range(start: -5m)\n|> filter(fn: (r) => r[\"_measurement\"] == \"shutter\" and r[\"dev\"] == \"nozzle\")\n|> last()\n|> sort (columns:[\"type\"], desc: false)\n|> drop(columns:[\"_time\"])"
    }
   ]
  },
  {
   "title": "${Ring_gauge} (mbar)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"experiment\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vacuum\" and r[\"dev\"] == \"${Ring_gauge}\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Inlet pressures (E1 - E4)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "query": "from(bucket: \"experiment\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vacuum\" and r[\"dev\"]=~ /GJ_E/)\n  |> aggregateWindow(every: v.windowPeriod, fn: last)"
    }
   ]
  },
  {
   "title": "Dump pressures (S1 - S4)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "query": "from(bucket: \"experiment\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vacuum\" and r[\"dev\"]=~ /GJ_S/)\n  |> aggregateWindow(every: v.windowPeriod, fn: last)"
    }
   ]
  },
  {
   "title": "Dump pressures (mbar)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"experiment\")\n  |> range(start: -1m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vacuum\" and r[\"dev\"] =~ /GJ_S/)\n  |> last()\n  |> drop(columns: [\"ch\"])\n  |> sort(columns: [\"dev\"], desc:true)"
    }
   ]
  }
 ]
}